export const SAMPLE_ERROR_CODE = {
	SAMPLE: "SAMPLE",
} as const;

export const COMMON_ERROR_CODE = {
	METHOD_ARGUMENT_TYPE_MISMATCH: "C001",
	METHOD_NOT_ALLOWED: "C002",
	INTERNAL_SERVER_ERROR: "C003",
} as const;

export const USER_ERROR_CODE = {
	NOT_FOUND: "U001",
} as const;

export const GEMINI_ERROR_CODE = {
	API_ERROR: "G001",
	RESPONSE_PARSE_ERROR: "G002",
} as const;

export const KAKAO_ERROR_CODE = {
	API_ERROR: "K001",
	RATE_LIMIT_EXCEEDED: "K002",
} as const;

export const RESTAURANT_ERROR_CODE = {
	COLLECTION_FAILED: "R001",
	INVALID_LOCATION_NAME: "R002",
	INVALID_CATEGORY_NAME: "R003",
	NOT_FOUND: "R004",
	CATEGORY_NOT_FOUND: "R005",
	SYNC_JOB_NOT_FOUND: "R006",
	SYNC_JOB_CONFLICT: "R007",
	SYNC_FAILED: "R008",
} as const;

export const GATHERING_ERROR_CODE = {
	NOT_FOUND: "GA001",
	DELETED: "GA002",
	FULL: "GA003",
	PEOPLE_COUNT_REQUIRED: "GA004",
	PEOPLE_COUNT_OUT_OF_RANGE: "GA005",
	SCHEDULED_DATE_REQUIRED: "GA006",
	SCHEDULED_DATE_PAST: "GA007",
} as const;

export const PARTICIPANT_ERROR_CODE = {
	DISLIKES_EXCEEDED: "P001",
	PREFERENCES_EXCEEDED: "P002",
	NICKNAME_REQUIRED: "P003",
	NICKNAME_TOO_LONG: "P004",
	NICKNAME_INVALID: "P005",
	DUPLICATE_NICKNAME: "P006",
	MAJORITY_NOT_REACHED: "P007",
} as const;

export const LOCK_ERROR_CODE = {
	TIMEOUT: "L001",
} as const;

export const RECOMMEND_ERROR_CODE = {
	INVALID_CATEGORY_AGGREGATION: "REC001",
	INVALID_PREFERENCE_SCORE: "REC002",
	ALREADY_PROCEEDED: "REC003",
} as const;

export const ADMIN_ERROR_CODE = {
	NOT_FOUND: "A001",
	INVALID_PASSWORD: "A002",
	UNAUTHORIZED: "A003",
	FORBIDDEN: "A004",
	TOKEN_EXPIRED: "A005",
	TOKEN_INVALID: "A006",
} as const;

export const ERROR_CODE = {
	...SAMPLE_ERROR_CODE,
	...COMMON_ERROR_CODE,
	...USER_ERROR_CODE,
	...GEMINI_ERROR_CODE,
	...KAKAO_ERROR_CODE,
	...RESTAURANT_ERROR_CODE,
	...GATHERING_ERROR_CODE,
	...PARTICIPANT_ERROR_CODE,
	...LOCK_ERROR_CODE,
	...RECOMMEND_ERROR_CODE,
	...ADMIN_ERROR_CODE,
} as const;

export type ApiErrorCode = string;

export const ERROR_MESSAGE_BY_CODE: Record<ApiErrorCode, string> = {
	[SAMPLE_ERROR_CODE.SAMPLE]: "Sample Error Message",
	[COMMON_ERROR_CODE.METHOD_ARGUMENT_TYPE_MISMATCH]:
		"요청 한 값 타입이 잘못되어 binding에 실패하였습니다.",
	[COMMON_ERROR_CODE.METHOD_NOT_ALLOWED]: "지원하지 않는 HTTP method 입니다.",
	[COMMON_ERROR_CODE.INTERNAL_SERVER_ERROR]: "서버 오류, 관리자에게 문의하세요",
	[USER_ERROR_CODE.NOT_FOUND]: "해당 회원을 찾을 수 없습니다.",
	[GEMINI_ERROR_CODE.API_ERROR]: "Gemini API 호출 실패",
	[GEMINI_ERROR_CODE.RESPONSE_PARSE_ERROR]: "Gemini 응답 파싱 실패",
	[KAKAO_ERROR_CODE.API_ERROR]: "Kakao API 호출 실패",
	[KAKAO_ERROR_CODE.RATE_LIMIT_EXCEEDED]:
		"Kakao API 요청 한도 초과",
	[RESTAURANT_ERROR_CODE.COLLECTION_FAILED]: "식당 수집 작업 실패",
	[RESTAURANT_ERROR_CODE.INVALID_LOCATION_NAME]: "알 수 없는 지역명입니다",
	[RESTAURANT_ERROR_CODE.INVALID_CATEGORY_NAME]:
		"알 수 없는 카테고리명입니다",
	[RESTAURANT_ERROR_CODE.NOT_FOUND]: "해당 맛집을 찾을 수 없습니다",
	[RESTAURANT_ERROR_CODE.CATEGORY_NOT_FOUND]:
		"해당 카테고리를 찾을 수 없습니다",
	[RESTAURANT_ERROR_CODE.SYNC_JOB_NOT_FOUND]:
		"해당 동기화 Job을 찾을 수 없습니다",
	[RESTAURANT_ERROR_CODE.SYNC_JOB_CONFLICT]:
		"이미 실행 중인 동기화 Job이 존재합니다",
	[RESTAURANT_ERROR_CODE.SYNC_FAILED]:
		"맛집 동기화 작업이 실패했습니다",
	[GATHERING_ERROR_CODE.NOT_FOUND]: "해당 모임을 찾을 수 없습니다",
	[GATHERING_ERROR_CODE.DELETED]: "이미 삭제된 모임입니다",
	[GATHERING_ERROR_CODE.FULL]: "모임 인원이 가득 찼습니다",
	[GATHERING_ERROR_CODE.PEOPLE_COUNT_REQUIRED]:
		"모임 인원 수는 필수입니다",
	[GATHERING_ERROR_CODE.PEOPLE_COUNT_OUT_OF_RANGE]:
		"모임 인원 수는 1 이상 10 이하여야 합니다",
	[GATHERING_ERROR_CODE.SCHEDULED_DATE_REQUIRED]:
		"모임 날짜는 필수입니다",
	[GATHERING_ERROR_CODE.SCHEDULED_DATE_PAST]:
		"과거 날짜로는 모임을 생성할 수 없습니다",
	[PARTICIPANT_ERROR_CODE.DISLIKES_EXCEEDED]:
		"비선호 음식은 최소 1개, 최대 2개까지 입력 가능합니다",
	[PARTICIPANT_ERROR_CODE.PREFERENCES_EXCEEDED]:
		"선호 음식은 최대 3개까지 입력 가능합니다",
	[PARTICIPANT_ERROR_CODE.NICKNAME_REQUIRED]: "닉네임은 필수입니다",
	[PARTICIPANT_ERROR_CODE.NICKNAME_TOO_LONG]:
		"닉네임은 최대 8자까지 입력 가능합니다",
	[PARTICIPANT_ERROR_CODE.NICKNAME_INVALID]:
		"닉네임에 숫자 또는 특수문자는 사용할 수 없습니다",
	[PARTICIPANT_ERROR_CODE.DUPLICATE_NICKNAME]:
		"이미 입장한 사용자입니다",
	[PARTICIPANT_ERROR_CODE.MAJORITY_NOT_REACHED]:
		"추천 진행을 위한 과반수 인원이 채워지지 않았습니다",
	[LOCK_ERROR_CODE.TIMEOUT]: "락 획득 시간이 초과되었습니다",
	[RECOMMEND_ERROR_CODE.INVALID_CATEGORY_AGGREGATION]:
		"카테고리 집계 데이터가 올바르지 않습니다",
	[RECOMMEND_ERROR_CODE.INVALID_PREFERENCE_SCORE]:
		"선호도 점수 상태가 올바르지 않습니다",
	[RECOMMEND_ERROR_CODE.ALREADY_PROCEEDED]:
		"이미 추천이 진행 중이거나 완료되었습니다",
	[ADMIN_ERROR_CODE.NOT_FOUND]: "해당 관리자를 찾을 수 없습니다",
	[ADMIN_ERROR_CODE.INVALID_PASSWORD]: "비밀번호가 일치하지 않습니다",
	[ADMIN_ERROR_CODE.UNAUTHORIZED]: "인증이 필요합니다",
	[ADMIN_ERROR_CODE.FORBIDDEN]: "접근 권한이 없습니다",
	[ADMIN_ERROR_CODE.TOKEN_EXPIRED]: "토큰이 만료되었습니다",
	[ADMIN_ERROR_CODE.TOKEN_INVALID]: "유효하지 않은 토큰입니다",
};
